### ISSUE TITLE
Removal of aggregates on markscheider side

### ISSUE THREAD

**Issue by Jan-M** [zalando-incubator/markscheider#10]
Hi there,

would you actually consider removing all the pre aggregates on the markscheider side?

From my side and usage within ZMON they confuse many of the easy aggregates in Grafana for example as you have sub aggregates not easy to remove (ALL.ALL, 2xx, 4xx, ...)

Br,
Jan

**Comment by musiKk** [comment]
@Jan-M I don't know why this has never been addressed. Sorry for that.

I see your point. While we're actually using some of these pre-aggregated values their meaningfulness is questionable. On the other hand this has been there before our Grafana setup had the wildcard feature.

If you still need it, I'd appreciate a pull request.
