### ISSUE TITLE
Support for Play 2.7 etc

### ISSUE THREAD

**Issue by lenalebt** [zalando-incubator/markscheider#26]
Hi together,
showing some love for my initial work (it's been a while...), I started updating the lib for Play 2.7 and added support for the prometheus metrics format. It's not ready for a PR yet, but I am willing to get it there if you would be open to accept a PR? Just wanted to ask before putting too much work in.

All the best,
Lena

**Comment by matterche** [comment]
Hi Lena,

Migration to Play 2.7 has already been done with https://github.com/zalando-incubator/markscheider/pull/25. However, contributions are always welcome.

**Comment by matterche** [comment]
Btw. @lenalebt maybe you have some thoughts on this one: https://github.com/zalando-incubator/markscheider/issues/22?

**Comment by lenalebt** [comment]
Hi Matthias,
oh, I must have overseen #25 - had a local fork that might have just been outdated. I added support for the prometheus metrics format additionally which may be useful for people interested. It still is a bit messy and I'd like to tidy it a little bit, but I'll add the PR some time in the next 2 weeks I think.

Will have a look at #22.
